apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment-19-07
spec:
  replicas: 2
  selector:
    matchLabels:
      app: assignment-19-07
  template:
    metadata:
      labels:
        app: assignment-19-07
    spec:
      containers:
      - name: assignment-container
        image: ganesh2296/jenkins-flask-app:latest
        ports:
        - containerPort: 80

